/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Enity.Firma;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXSearchField;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Przemek
 */
public class listaDostawcaView extends javax.swing.JFrame {

    /**
     * Creates new form DostawcaLstaView
     */
    public listaDostawcaView() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Lista Distawców");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jXTable5 = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Nowy");

        jButton2.setText("Odśwież");

        jXTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa", "NIP", "nr budynku", "nr lokalu", "ulica", "kod Pocztowy", "Miejscowosc", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable5.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jXTable5);
        if (jXTable5.getColumnModel().getColumnCount() > 0) {
            jXTable5.getColumnModel().getColumn(7).setMinWidth(0);
            jXTable5.getColumnModel().getColumn(7).setPreferredWidth(0);
            jXTable5.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JXSearchField getjXSearchField1() {
        return jXSearchField1;
    }

    public void setjXSearchField1(JXSearchField jXSearchField1) {
        this.jXSearchField1 = jXSearchField1;
    }

    public JXTable getjXTable5() {
        return jXTable5;
    }

    public void setjXTable5(JXTable jXTable5) {
        this.jXTable5 = jXTable5;
    }

    public void wypisz(DefaultTableModel DTM, ArrayList<Firma> lista) {
        for (int i = 0; i < lista.size(); i++) {
            DTM.insertRow(i, new Object[]{lista.get(i).getNazwa(), lista.get(i).getNip(),
                lista.get(i).getNrBudynku(), lista.get(i).getNrLokalu(), lista.get(i).getUlica(),
                lista.get(i).getKodPocztowy(), lista.get(i).getMiejscowosc(), lista.get(i).getId()});

        }
    }

    //Listeners set
    public void addJxSearchLis(ActionListener aL) {
        jXSearchField1.addActionListener(aL);
    }

    public void addjButton2Lis(ActionListener aL) {
        jButton2.addActionListener(aL);
    }

    public void addjButton1Lis(ActionListener aL) {
        jButton1.addActionListener(aL);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane6;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXTable jXTable5;
    // End of variables declaration//GEN-END:variables
}
