/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Enity.Towar;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.JXSearchField;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Przemek
 */
public class listaTowarView extends javax.swing.JFrame {

    /**
     * Creates new form WZ
     */
    public DefaultTableModel model;

    public listaTowarView() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        model = (DefaultTableModel) jXTable2.getModel();
        this.setVisible(true);
        this.setTitle("Lista Towarów");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    public JXSearchField getjXSearchField1() {
        return jXSearchField1;
    }

    public void setjXSearchField1(JXSearchField jXSearchField1) {
        this.jXSearchField1 = jXSearchField1;
    }

    public JXTable getjXTable2() {
        return jXTable2;
    }

    public void setjXTable2(JXTable jXTable2) {
        this.jXTable2 = jXTable2;
    }

    public void addListenerJxtable(MouseListener mL) {
        jXTable2.addMouseListener(mL);
    }

    public void addListenerJxsearch(ActionListener aL) {
        jXSearchField1.addActionListener(aL);
    }

    public void addListenerJbutton(ActionListener aL) {
        jButton1.addActionListener(aL);
    }

    public void addListenerOdswierz(ActionListener aL) {
        jButton2.addActionListener(aL);
    }

    public void wypisz(ArrayList<Towar> AL) {
        model.setRowCount(0);
        int size = AL.size();
        for (int i = 0; i < size; i++) {
            model.addRow(new Object[]{AL.get(i).getNazwa(), AL.get(i).getKodTowaru(), AL.get(i).getKodKreskowy(), AL.get(i).getDostepne(), AL.get(i).getJednostkaMiary(), AL.get(i).getId().toString()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        canvas1 = new java.awt.Canvas();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable2 = new org.jdesktop.swingx.JXTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa", "kod", "kod kreskowy", "Ilosc", "j.m", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jXTable2);
        if (jXTable2.getColumnModel().getColumnCount() > 0) {
            jXTable2.getColumnModel().getColumn(1).setMinWidth(125);
            jXTable2.getColumnModel().getColumn(1).setPreferredWidth(125);
            jXTable2.getColumnModel().getColumn(1).setMaxWidth(125);
            jXTable2.getColumnModel().getColumn(2).setMinWidth(200);
            jXTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
            jXTable2.getColumnModel().getColumn(2).setMaxWidth(200);
            jXTable2.getColumnModel().getColumn(3).setMinWidth(150);
            jXTable2.getColumnModel().getColumn(3).setPreferredWidth(150);
            jXTable2.getColumnModel().getColumn(3).setMaxWidth(150);
            jXTable2.getColumnModel().getColumn(4).setMinWidth(90);
            jXTable2.getColumnModel().getColumn(4).setPreferredWidth(90);
            jXTable2.getColumnModel().getColumn(4).setMaxWidth(90);
            jXTable2.getColumnModel().getColumn(5).setMinWidth(0);
            jXTable2.getColumnModel().getColumn(5).setPreferredWidth(0);
            jXTable2.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jButton1.setText("Nowy");

        jButton2.setText("Odśwież");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    public org.jdesktop.swingx.JXTable jXTable2;
    // End of variables declaration//GEN-END:variables
}
