/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.nowyTowarModel;
import Enity.JednostkaMiary;
import Enity.Kategoria;
import Enity.Towar;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Przemek
 */
public class nowyTowarView extends javax.swing.JFrame {

    /**
     * Creates new form nowyTowarView
     */
    private nowyTowarModel nTModel;

    public nowyTowarView(nowyTowarModel nTModel) {
        initComponents();
        this.nTModel = nTModel;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        teaOpis = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtKodKreskowy = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPKWiU = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKodTowaru = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNazwa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "23", "8", "5", "0" }));

        teaOpis.setColumns(20);
        teaOpis.setRows(5);
        jScrollPane1.setViewportView(teaOpis);

        jLabel3.setText("Jednostka Miary");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "szt.", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Kod Towaru");

        jLabel1.setText("Nazwa");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meble", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Kod Kreskowy");

        jLabel2.setText("Opis");

        jLabel6.setText("PKWiU");

        jButton3.setText("Nowa j.m.");

        jLabel7.setText("Kategoria");

        jButton4.setText("Nowa Kategoria");

        jLabel8.setText("VAT");

        jButton2.setText("Anuluj");

        jButton1.setText("Dodaj Towar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtNazwa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodTowaru)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPKWiU, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKodKreskowy)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKodTowaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKodKreskowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPKWiU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Kategoria newKategoria() {

        JTextField jtfNazwa = new JTextField();
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Nazwa"));
        panel.add(jtfNazwa);
        String strNazwa = "";

        int result = JOptionPane.showConfirmDialog(null, panel, "Nowa Kategoria",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            strNazwa = jtfNazwa.getText();
        }
        Kategoria kategoria = new Kategoria();
        kategoria.setNazwa(strNazwa);
        return kategoria;
    }

    public JednostkaMiary newJednostkaMiary() {
        JTextField jtfNazwa = new JTextField();
        JTextField jtfSkrot = new JTextField();
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Nazwa"));
        panel.add(jtfNazwa);
        panel.add(new JLabel("Sktót"));
        panel.add(jtfSkrot);
        String strNazwa = "";
        String strSkrot = "";
        int result = JOptionPane.showConfirmDialog(null, panel, "Nowa Jednostka Miary",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            strNazwa = jtfNazwa.getText();
            strSkrot = jtfSkrot.getText();

        }
        JednostkaMiary jm = new JednostkaMiary();
        jm.setNazwa(strNazwa);
        jm.setSkrot(strSkrot);

        return jm;
    }

    public void showMessage(String text) {
        JOptionPane.showMessageDialog(null, text, "", JOptionPane.INFORMATION_MESSAGE);
    }

    public void errorMessage(String tresc, String tytul) {
        JOptionPane.showMessageDialog(null, tresc, tytul, JOptionPane.ERROR_MESSAGE);
    }

    public String getKod() {
        return txtKodTowaru.getText();
    }

    public String getNazwa() {
        return txtNazwa.getText();
    }

    public Towar getTowar() {
        Kategoria kat = (Kategoria) jComboBox2.getSelectedItem();
        String IdKategoria = kat.getId().toString();

        JednostkaMiary jednoMiary = (JednostkaMiary) jComboBox1.getSelectedItem();
        String IdJednostkaMiary = jednoMiary.getId().toString();

        String Nazwa = txtNazwa.getText();
        String Opis = teaOpis.getText();
        String kodTow = txtKodTowaru.getText();
        String kodKre = txtKodKreskowy.getText();
        String Pkwiu = txtPKWiU.getText();

        Object cmboitem = jComboBox3.getSelectedItem();
        String VAT = (String) cmboitem;

        Towar towar = new Towar();
        towar.setNazwa(Nazwa);
        towar.setOpis(Opis);
        towar.setKategoria(IdKategoria);
        towar.setKodKreskowy(kodKre);
        towar.setKodTowaru(kodTow);
        towar.setPKWiU(Pkwiu);
        towar.setVAT(VAT);
        towar.setJednostkaMiary(IdJednostkaMiary);

        return towar;
    }

    public void wypiszKategoria(ArrayList<Kategoria> lista) {
        int liczba = lista.size();
        jComboBox2.removeAllItems();
        for (int i = 0; i < liczba; i++) {
            jComboBox2.addItem(lista.get(i));
        }
    }

    public void wypiszJM(ArrayList<JednostkaMiary> lista) {
        int liczba = lista.size();
        jComboBox1.removeAllItems();
        for (int i = 0; i < liczba; i++) {
            jComboBox1.addItem(lista.get(i));
        }
    }

    public void addDodajLis(ActionListener aL) {
        jButton1.addActionListener(aL);
    }

    public void addAnulujLis(ActionListener aL) {
        jButton2.addActionListener(aL);
    }

    public void addNowaJMLis(ActionListener aL) {
        jButton3.addActionListener(aL);
    }

    public void addNowaKategLis(ActionListener aL) {
        jButton4.addActionListener(aL);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea teaOpis;
    private javax.swing.JTextField txtKodKreskowy;
    private javax.swing.JTextField txtKodTowaru;
    private javax.swing.JTextField txtNazwa;
    private javax.swing.JTextField txtPKWiU;
    // End of variables declaration//GEN-END:variables

}
