/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Other;

import Model.listaTowarModel;
import Enity.Towar;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Przemek
 */
public final class wybierzTowar extends javax.swing.JPanel {

    /**
     * Creates new form wybierzTowar
     */
    public listaTowarModel tlM;
    public DefaultTableModel model;
    public String SelectedID = "0";
    public wybierzTowar(listaTowarModel tlM) throws SQLException {
        initComponents();
        this.tlM = tlM;
        model = (DefaultTableModel) jXTable2.getModel();
        tlM.setSearchSting("");
        wypisz(tlM.SelectTowar());
    }

    public void wypisz(ArrayList<Towar> AL) {
        model.setRowCount(0);
        int size = AL.size();
        for (int i = 0; i < size; i++) {
            model.addRow(new Object[]{AL.get(i).getNazwa(), AL.get(i).getKodTowaru(), AL.get(i).getKodKreskowy(), AL.get(i).getDostepne(), AL.get(i).getJednostkaMiary(), AL.get(i).getId().toString()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable2 = new org.jdesktop.swingx.JXTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa", "kod", "kod kreskowy", "Ilosc", "j.m", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jXTable2);
        if (jXTable2.getColumnModel().getColumnCount() > 0) {
            jXTable2.getColumnModel().getColumn(1).setMinWidth(100);
            jXTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jXTable2.getColumnModel().getColumn(1).setMaxWidth(100);
            jXTable2.getColumnModel().getColumn(2).setMinWidth(100);
            jXTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jXTable2.getColumnModel().getColumn(2).setMaxWidth(100);
            jXTable2.getColumnModel().getColumn(3).setMinWidth(100);
            jXTable2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jXTable2.getColumnModel().getColumn(3).setMaxWidth(100);
            jXTable2.getColumnModel().getColumn(4).setMinWidth(70);
            jXTable2.getColumnModel().getColumn(4).setPreferredWidth(70);
            jXTable2.getColumnModel().getColumn(4).setMaxWidth(70);
            jXTable2.getColumnModel().getColumn(5).setMinWidth(0);
            jXTable2.getColumnModel().getColumn(5).setPreferredWidth(0);
            jXTable2.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jXSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXSearchField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(490, 490, 490)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jXSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXSearchField1ActionPerformed
        // TODO add your handling code here:
        tlM.setSearchSting(jXSearchField1.getText());
        try {
            wypisz(tlM.SelectTowar());
        } catch (SQLException ex) {
            Logger.getLogger(wybierzTowar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXSearchField1ActionPerformed

    private void jXTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable2MouseClicked
        // TODO add your handling code here:
        SelectedID = (String) jXTable2.getValueAt(jXTable2.getSelectedRow(), 5);
    }//GEN-LAST:event_jXTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    public org.jdesktop.swingx.JXTable jXTable2;
    // End of variables declaration//GEN-END:variables
}
