/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;


import db.Connector;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.renderer.DefaultTableRenderer;

/**
 *
 * @author Przemek
 */
public class CennikInd extends javax.swing.JPanel {

    /**
     * Creates new form CennikInd
     */
    Connector con ;
    DefaultTableModel model;
    public CennikInd(Connector con) throws SQLException {
        initComponents();
        this.con=con;
         model = (DefaultTableModel) jXTable1.getModel();
         //jXTable1.getColumnExt(2).setCellRenderer(new DefaultTableCellRenderer);
         wypiszDB();
    }
    
      public void wypiszDB() throws SQLException {
        String query;
        query = "   SELECT Towar.Nazwa, Cena, DataPoczatkowa, DataKoncowa, Firma.Nazwa, Towar.VAT FROM TOWAR "
                + " INNER JOIN  CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                +" INNER JOIN Firma ON CennikIndywidualny.IdKlient=Firma.Id";
        ResultSet rs = con.querySelect(query);

        while (rs.next()) {
            Double VAT;
            Double Netto=0.0;
            Double Brutto=0.0;
            try{
                VAT = Double.parseDouble(rs.getString(6));
                Netto = Double.parseDouble(rs.getString(2));
                VAT = VAT/100;
                Brutto = Netto*VAT+Netto;
                
            }catch(NullPointerException ex){}
            
            
            
            DecimalFormat df = new DecimalFormat("#,###.00");
            model.addRow(new Object[]{rs.getString(1),rs.getString(5)
                    ,df.format(Netto),df.format(Brutto) ,rs.getDate(3), rs.getDate(4)});
         
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        jButton1.setText("Nowa Cena");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa Towaru", "Klient", "Cena Netto", "Cena Brutto", "Data Od", "Data Do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jXTable1);
        if (jXTable1.getColumnModel().getColumnCount() > 0) {
            jXTable1.getColumnModel().getColumn(2).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(2).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(3).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(3).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(4).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(4).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(5).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(5).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(5).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 746, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JPanel jp = new JPanel();

        listaTowarow lt = null;
        listaKlient lk =null;
        
        jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
        panelCena pc = new panelCena();

        try {
            lt = new listaTowarow(con, 1);
            jp.add(lt);
            lk = new listaKlient(con,1);
            jp.add(lk);
            jp.add(pc);
            
            int response = JOptionPane.showConfirmDialog(null, jp, "",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if(response==0){
            Double brutto;
            
            
            Date dw =pc.jXDatePicker1.getDate();
        
         
        SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
        String date = DATE_FORMAT.format(dw);
        String date2;
        try {
         date2 = DATE_FORMAT.format(pc.jXDatePicker2.getDate());
        }catch (Exception e){
        date2="null";
        }
       
            brutto = Double.parseDouble(pc.jTextField2.getText()) * 1.23;
            model.addRow(new Object[]{lt.SelectNazwa, pc.jTextField2.getText(), brutto.toString()});
            
            String query = 
                     " INSERT INTO CennikIndywidualny(IdTowar,IdKlient ,Cena, DataPoczatkowa, DataKoncowa) VALUES ("+lt.SelectID+","+lk.selectID+","+pc.jTextField2.getText()+",'"+date+"','"+date2+"')";
           con.query(query);
            model.setRowCount(0);
            wypiszDB();}
        } catch (SQLException ex) {
            Logger.getLogger(Klient_CenyInd.class.getName()).log(Level.SEVERE, null, ex);

            // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
