/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import db.Connector;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Przemek
 */
public final class edycjaFaktura extends javax.swing.JPanel {

    private   DefaultTableModel model;
    private String IdFirma;
    private final Connector con;
    private Object formaPatnosci;
    private final String IdFaktura;
    private final JFrame f;
    private String query1="";
 private final DecimalFormat df = new DecimalFormat("##0.00");
    /**
     * Creates new form NewJPanel
     * @param con
     * @param IdFaktura
     * @param f
     * @throws java.sql.SQLException
     */
    public edycjaFaktura(Connector con, String IdFaktura, JFrame f) throws SQLException {
        initComponents();
        this.con = con;
        this.f = f;
        this.IdFaktura = IdFaktura;
        jComboBox1.removeAllItems();

        model = (DefaultTableModel) jXTable1.getModel();
        model.setRowCount(0);

        wypisz();

        jComboBox1.addItem("Gotówka");
        jComboBox1.addItem("Przelew 7 dni");
        jComboBox1.addItem("Przelew 14 dni");
        jComboBox1.addItem("Przelew");
    }

    public void wypisz() throws SQLException {

        String query = "SELECT * FROM Faktura WHERE Id= " + IdFaktura;

        ResultSet rs = con.querySelect(query);

        while (rs.next()) {

            txtNrDok.setText(rs.getString(2));
            IdFirma = rs.getString(8);
            jTextField1.setText(rs.getString(9));
            dateDWystawienia.setDate(rs.getDate(3));
            jXDatePicker2.setDate(rs.getDate(4));
            jTextArea1.setText(rs.getString(7));
            jTextArea2.setText(rs.getString(6));
            jComboBox1.addItem(rs.getString(5));
            jXDatePicker1.setDate(rs.getDate(14));
        }

        query = " SELECT * FROM PozycjaFaktury INNER JOIN Towar ON Towar = Towar.Id where IdFaktura = " + IdFaktura;

        rs = con.querySelect(query);

        while (rs.next()) {
            Double dostep = rs.getDouble(4) + rs.getDouble(20);
            model.addRow(new Object[]{rs.getString(12), rs.getString(4), rs.getString(8), rs.getDouble(5), rs.getDouble(6), "", "", "", rs.getString(2), dostep, rs.getString(4)});

        }
        licz();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNrDok = new javax.swing.JTextField();
        dateDWystawienia = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();

        jButton3.setText("Usuń");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Suma BRUTTO");

        jLabel9.setBackground(new java.awt.Color(0, 204, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("0 ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("zł");

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa Towaru", "Ilość", "j.m", "Cena Netto", "VAT", "Wartość Netto", "Wartość VAT", "Wartość Brutto", "ID", "dostepne", "iloscOLD", "dostepOLD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.getTableHeader().setReorderingAllowed(false);
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jXTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jXTable1);
        if (jXTable1.getColumnModel().getColumnCount() > 0) {
            jXTable1.getColumnModel().getColumn(1).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(1).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(2).setMinWidth(75);
            jXTable1.getColumnModel().getColumn(2).setPreferredWidth(75);
            jXTable1.getColumnModel().getColumn(2).setMaxWidth(75);
            jXTable1.getColumnModel().getColumn(3).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(3).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jXTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jXTable1.getColumnModel().getColumn(4).setMaxWidth(50);
            jXTable1.getColumnModel().getColumn(5).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(5).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(5).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(6).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(6).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(7).setMinWidth(120);
            jXTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
            jXTable1.getColumnModel().getColumn(7).setMaxWidth(120);
            jXTable1.getColumnModel().getColumn(8).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(8).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(8).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(9).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(9).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(9).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(10).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(10).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(10).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(11).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(11).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        jTextField1.setColumns(20);
        jTextField1.setRows(5);
        jScrollPane4.setViewportView(jTextField1);

        jLabel1.setText("Kontrahent");

        jLabel2.setText("Numer dokumentu");

        dateDWystawienia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDWystawieniaActionPerformed(evt);
            }
        });

        jLabel3.setText("Data wystawienia");

        jLabel4.setText("Termin płatności");

        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Kod towaru");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gotówka", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel5.setText("Forma płatnosci");

        jLabel6.setText("Uwagi");

        jLabel7.setText("Notatka");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Zapisz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Zapisz i drukuj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Anuluj");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Data Sprzedaży");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNrDok, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateDWystawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNrDok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(dateDWystawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jLabel12)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)))
        );
    }// </editor-fold>//GEN-END:initComponents
   private void UpdateCeny() throws SQLException {

        for (int i = 0; i < model.getRowCount(); i++) {
            String query = null;
            SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");      String dataS= DATE_FORMAT.format(jXDatePicker1.getDate());

            query = "IF EXISTS (SELECT * FROM TOWAR "
                    + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                    + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                    + "LEFT JOIN CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                    + "WHERE "
                    + "(CennikIndywidualny.DataKoncowa IS NULL OR  '"+dataS+"' <= CennikIndywidualny.DataKoncowa) AND '"+dataS+"' >= CennikIndywidualny.DataPoczatkowa AND CennikIndywidualny.IdKlient= " + IdFirma + " AND Towar.Id = " + jXTable1.getValueAt(i, 8) + " )  "
                    + "SELECT Towar.Id, Towar.Nazwa, Towar.PKWiU, JednostkaMiary.skrot, CennikIndywidualny.Cena, CennikIndywidualny.Id, Towar.VAT  FROM TOWAR "
                    + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                    + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                    + "LEFT JOIN CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                    + "WHERE (CennikIndywidualny.DataKoncowa IS NULL OR  '"+dataS+"' <= CennikIndywidualny.DataKoncowa) AND '"+dataS+"' >= CennikIndywidualny.DataPoczatkowa AND CennikIndywidualny.IdKlient= " + IdFirma + " AND Towar.Id = " + jXTable1.getValueAt(i, 8) + "  "
                    + "ORDER BY CennikIndywidualny.Id DESC "
                    + "ELSE "
                    + "SELECT Towar.Id, Towar.Nazwa, Towar.PKWiU, JednostkaMiary.skrot, Cennik.Cena, Cennik.ID, Towar.VAT  FROM TOWAR "
                    + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                    + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                    + "LEFT JOIN Cennik ON Towar.Id = Cennik.IdTowar "
                    + "WHERE (Cennik.DataKoncowa IS NULL OR  '"+dataS+"' <= Cennik.DataKoncowa) AND '"+dataS+"' >= Cennik.DataPoczatkowa AND Towar.Id = " + jXTable1.getValueAt(i, 8) + " ORDER BY Cennik.Id DESC";

            ResultSet rs = con.querySelect(query);
 
            while (rs.next()) {
                
                jXTable1.getColumnExt(3).setEditable(true);
                jXTable1.setValueAt(df.format(rs.getDouble(5)), i, 3);
                jXTable1.getColumnExt(3).setEditable(false);
                break;
            }

        }
        licz();
    }

    private void ustawDate() {

        if ("Przelew 7 dni".equals(formaPatnosci)) {
            Date dw = dateDWystawienia.getDate();
            Date next;
            try {
                next = new Date(dw.getTime() + (8 * 1000 * 60 * 60 * 24));
            } catch (NullPointerException | IllegalArgumentException ex) {
                next = new Date(new Date().getTime() + (8 * 1000 * 60 * 60 * 24));
            }
            jXDatePicker2.setDate(next);
            jXDatePicker2.setEditable(false);
        }

        if ("Przelew 14 dni".equals(formaPatnosci)) {
            Date dw = dateDWystawienia.getDate();
            Date next;
            try {
                next = new Date(dw.getTime() + (15 * 1000 * 60 * 60 * 24));
            } catch (NullPointerException ex) {
                next = new Date(new Date().getTime() + (15 * 1000 * 60 * 60 * 24));
            } catch (IllegalArgumentException ex) {
                next = new Date(new Date().getTime() + (15 * 1000 * 60 * 60 * 24));
            }
            jXDatePicker2.setDate(next);
            jXDatePicker2.setEditable(false);
        }

        if ("Gotówka".equals(formaPatnosci)) {
            Date dw = dateDWystawienia.getDate();
            Date next;
            try {
                next = new Date(dw.getTime());
            } catch (NullPointerException | IllegalArgumentException ex) {
                next = new Date(new Date().getTime());
            }
            jXDatePicker2.setDate(next);
            jXDatePicker2.setEditable(false);
        }

        if ("Przelew".equals(formaPatnosci)) {

            jXDatePicker2.setEditable(true);
        }

    }

    private void licz() {
        Double suma;
        suma = 0.00;
        for (int i = 0; i < jXTable1.getRowCount(); i++) {
            String ilosc = jXTable1.getValueAt(i, 1).toString().replaceAll(",", ".") ;
            String cNetto = jXTable1.getValueAt(i, 3).toString().replaceAll(",", ".") ;
            String VAT = jXTable1.getValueAt(i, 4).toString().replaceAll(",", ".") ;

            Double il, cN, V;
            try {
                il = Double.parseDouble(ilosc);
                cN = Double.parseDouble(cNetto);
                V = Double.parseDouble(VAT);

                Double wNetto = il * cN;
                Double wVAT = (il * V * cN) / 100;
                Double wBrutto = wNetto + wVAT;

                jXTable1.getColumnExt(5).setEditable(true);
                jXTable1.getColumnExt(6).setEditable(true);
                jXTable1.getColumnExt(7).setEditable(true);

                jXTable1.setValueAt(wNetto, i, 5);
                jXTable1.setValueAt(wVAT.toString(), i, 6);
                jXTable1.setValueAt(wBrutto.toString(), i, 7);

                jXTable1.getColumnExt(5).setEditable(false);
                jXTable1.getColumnExt(6).setEditable(false);
                jXTable1.getColumnExt(7).setEditable(false);

                suma = suma + wBrutto;
            } catch (NumberFormatException e) {
            }

        }
        jLabel9.setText(df.format(suma));

    }

    public void walidacjaIlosc() {
        Double ilosc = 0.0;
        Double dostepne = 0.0;
        try {
            ilosc = Double.parseDouble(jXTable1.getValueAt(jXTable1.getSelectedRow(), 1).toString());
        } catch (NumberFormatException e) {
            dostepne = 0.0;
        }
        try {
            dostepne = Double.parseDouble(jXTable1.getValueAt(jXTable1.getSelectedRow(), 9).toString());
        } catch (NumberFormatException | NullPointerException e) {
            jXTable1.setValueAt("0", jXTable1.getSelectedRow(), 9);
            dostepne = 0.0;
        }

        if (ilosc > dostepne) {
            JOptionPane.showMessageDialog(null, "Podana ilość towaru jest większa od posiadanej\n", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            jXTable1.setValueAt(dostepne, jXTable1.getSelectedRow(), 1);
            jXTable1MouseClicked(null);
        }
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // usuwanie wiersza towarów

   query1 += "UPDATE Towar SET dostepne = dostepne +" + jXTable1.getValueAt(jXTable1.getSelectedRow(), 10).toString() + " where id = " + jXTable1.getValueAt(jXTable1.getSelectedRow(), 8).toString();;
       
    

        model.removeRow(jXTable1.getSelectedRow());
        licz();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
        walidacjaIlosc();

        licz();
    }//GEN-LAST:event_jXTable1MouseClicked

    private void jXTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTable1KeyReleased
        walidacjaIlosc();
        licz();
    }//GEN-LAST:event_jXTable1KeyReleased

    private void dateDWystawieniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDWystawieniaActionPerformed

        ustawDate();
    }//GEN-LAST:event_dateDWystawieniaActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed

    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        Object cmboitem = jComboBox1.getSelectedItem();
        formaPatnosci = (String) cmboitem;
        ustawDate();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (IdFirma.equals("0")) {
                JOptionPane.showMessageDialog(null, "Proszę wybrać kliena", "INFO", JOptionPane.INFORMATION_MESSAGE);
            } else {

                try {

                    String query;
SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");      String dataS= DATE_FORMAT.format(jXDatePicker1.getDate());

                    query = "IF EXISTS (SELECT * FROM TOWAR "
                            + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                            + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                            + "LEFT JOIN CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                            + "WHERE "
                            + "(CennikIndywidualny.DataKoncowa IS NULL OR  '"+dataS+"' <= CennikIndywidualny.DataKoncowa) AND '"+dataS+"' >= CennikIndywidualny.DataPoczatkowa AND CennikIndywidualny.IdKlient= " + IdFirma + " AND Towar.KodTowaru = '" + jTextField3.getText() + "' )  "
                            + "SELECT Towar.Id, Towar.Nazwa, Towar.PKWiU, JednostkaMiary.skrot, CennikIndywidualny.Cena, CennikIndywidualny.Id, Towar.VAT, Towar.dostepne, Towar.KodTowaru FROM TOWAR "
                            + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                            + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                            + "LEFT JOIN CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                            + "WHERE (CennikIndywidualny.DataKoncowa IS NULL OR  '"+dataS+"' <= CennikIndywidualny.DataKoncowa) AND '"+dataS+"' >= CennikIndywidualny.DataPoczatkowa AND CennikIndywidualny.IdKlient= " + IdFirma + " AND Towar.KodTowaru = '"
                            + jTextField3.getText() + "'  "
                            + "ORDER BY CennikIndywidualny.Id DESC "
                            + "ELSE "
                            + "SELECT Towar.Id, Towar.Nazwa, Towar.PKWiU, JednostkaMiary.skrot, Cennik.Cena, Cennik.ID, Towar.VAT, Towar.dostepne FROM TOWAR "
                            + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                            + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                            + "LEFT JOIN Cennik ON Towar.Id = Cennik.IdTowar "
                            + "WHERE (Cennik.DataKoncowa IS NULL OR  '"+dataS+"' <= Cennik.DataKoncowa) AND '"+dataS+"' >= Cennik.DataPoczatkowa AND Towar.KodTowaru = '" + jTextField3.getText() + "' ORDER BY Cennik.Id DESC";

                    ResultSet rs = con.querySelect(query);

                   while (rs.next()) {
                    if(uzytoTowar(rs.getString(1))){
                    model.addRow(new Object[]{rs.getString(2), "", rs.getString(4), df.format(rs.getDouble(5)), rs.getString(7), "", "", "", rs.getString(1), rs.getString(8)});
                    break;}
                    else  {JOptionPane.showMessageDialog(null, "Wybrany towar znajduje się już na fakturze.\n"
                            + "Proszę zwiększuć ilość towaru w istniejącym wierszu", "INFO", JOptionPane.INFORMATION_MESSAGE);
                    break;}
                }

                } catch (SQLException ex) {
                    Logger.getLogger(nowaFaktura.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // wybór towaru z listy towarów
        if (IdFirma.equals("0")) {
            JOptionPane.showMessageDialog(null, "Proszę wybrać kliena", "INFO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            listaTowarow lt;
            try {
                lt = new listaTowarow(con, 1);

                JOptionPane.showConfirmDialog(null, lt, "Wybierz Towar",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

                String query;

                   SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");      String dataS= DATE_FORMAT.format(jXDatePicker1.getDate());

                query = "IF EXISTS (SELECT * FROM TOWAR "
                        + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                        + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                        + "LEFT JOIN CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                        + "WHERE "
                        + "(CennikIndywidualny.DataKoncowa IS NULL OR  '"+dataS+"' <= CennikIndywidualny.DataKoncowa) AND '"+dataS+"' >= CennikIndywidualny.DataPoczatkowa AND CennikIndywidualny.IdKlient= " + IdFirma + " AND Towar.Id = " + lt.SelectID + " )  "
                        + "SELECT Towar.Id, Towar.Nazwa, Towar.PKWiU, JednostkaMiary.skrot, CennikIndywidualny.Cena, CennikIndywidualny.Id, Towar.VAT, Towar.dostepne FROM TOWAR "
                        + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                        + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                        + "LEFT JOIN CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                        + "WHERE (CennikIndywidualny.DataKoncowa IS NULL OR '"+dataS+"' <= CennikIndywidualny.DataKoncowa) AND '"+dataS+"' >= CennikIndywidualny.DataPoczatkowa AND CennikIndywidualny.IdKlient= " + IdFirma + " AND Towar.Id = " + lt.SelectID + "  "
                        + "ORDER BY CennikIndywidualny.Id DESC "
                        + "ELSE "
                        + "SELECT Towar.Id, Towar.Nazwa, Towar.PKWiU, JednostkaMiary.skrot, Cennik.Cena, Cennik.ID, Towar.VAT, Towar.dostepne FROM TOWAR "
                        + "INNER JOIN Kategoria ON Towar.IdKategoria = Kategoria.Id "
                        + "INNER JOIN JednostkaMiary ON Towar.JednostkaMiary = JednostkaMiary.Id "
                        + "LEFT JOIN Cennik ON Towar.Id = Cennik.IdTowar "
                        + "WHERE (Cennik.DataKoncowa IS NULL OR  '"+dataS+"' <= Cennik.DataKoncowa) AND '"+dataS+"' >= Cennik.DataPoczatkowa AND Towar.Id = " + lt.SelectID + " ORDER BY Cennik.Id DESC";


                ResultSet rs = con.querySelect(query);

                while (rs.next()) {
                    if(uzytoTowar(rs.getString(1))){
                    model.addRow(new Object[]{rs.getString(2), "", rs.getString(4), df.format(rs.getDouble(5)), rs.getString(7), "", "", "", rs.getString(1), rs.getString(8)});
                    break;}
                    else  {JOptionPane.showMessageDialog(null, "Wybrany towar znajduje się już na fakturze.\n"
                            + "Proszę zwiększuć ilość towaru w istniejącym wierszu", "INFO", JOptionPane.INFORMATION_MESSAGE);
                    break;}
                }
            } catch (SQLException ex) {
                Logger.getLogger(nowaFaktura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 private boolean uzytoTowar(String id) {
        for (int i = 0; i<jXTable1.getRowCount();i++)
        {
            if( jXTable1.getValueAt(i, 8).equals(id)){return false;}
        }
        return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        boolean validate = true;

        for (int i = 0; i < model.getRowCount(); i++) {
            String str = jXTable1.getValueAt(i, 1).toString();
            if (str.equals("")) {

                JOptionPane.showMessageDialog(null, "Proszę uzupełnić dane ", "INFO", JOptionPane.INFORMATION_MESSAGE);
                validate = false;
                break;
            }
        }
        if (validate && model.getRowCount() > 0) {

            String query;

            query = "DELETE FROM PozycjaFaktury WHERE IdFaktura =" + IdFaktura;
System.out.println(query);
            con.query(query);
            Object cmboitem = jComboBox1.getSelectedItem();
            formaPatnosci = (String) cmboitem;
            SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
            String dateP = DATE_FORMAT.format(jXDatePicker2.getDate());
            String dateS = DATE_FORMAT.format(jXDatePicker1.getDate());
            String dateW = DATE_FORMAT.format(dateDWystawienia.getDate());
            query = "UPDATE Faktura SET "
                    + "TerminZaplaty = '" + dateP + "', "
                    + "FormaZaplaty = '" + formaPatnosci + "', "
                    + "DataSprzedazy = '" + dateS + "', "
                    + "DataWystawienia = '" + dateW + "', "
                    + "Uwagi = '" + jTextArea2.getText() + "', "
                    + "Notatki = '" + jTextArea1.getText() + "', "
                    + "wartoscBrutto = '" + jLabel9.getText().replaceAll(",", ".") + "' WHERE Id = " + IdFaktura;
            con.query(query);
            for (int i = 0; i < model.getRowCount(); i++) {

                try {

                    query = "UPDATE Towar SET dostepne = dostepne +" + jXTable1.getValueAt(jXTable1.getSelectedRow(), 10).toString() + " where id = " + jXTable1.getValueAt(jXTable1.getSelectedRow(), 8).toString();
                    con.query(query);
                        System.out.println(query);
                } catch (NullPointerException | IndexOutOfBoundsException ex) {
                }

                query = "INSERT INTO PozycjaFaktury (Towar, IdFaktura, ilosc, CenaNetto, VAT, jm) VALUES("
                        + " '" + jXTable1.getValueAt(i, 8).toString() + "',"
                        + " " + IdFaktura + ", "
                        + " '" + jXTable1.getValueAt(i, 1).toString().replaceAll(",", ".") + "', " //ilosc
                        + " '" + jXTable1.getValueAt(i, 3).toString().replaceAll(",", ".") + "', " // cena netto
                        + " '" + jXTable1.getValueAt(i, 4).toString().replaceAll(",", ".") + "', " // Vat%
                        + " '" + jXTable1.getValueAt(i, 2).toString().replaceAll(",", ".") + "' " // jm
                        + ")";

                con.query(query);
                System.out.println(query);
                query = "UPDATE Towar SET dostepne = dostepne -" + jXTable1.getValueAt(i, 1).toString() + " where id = " + jXTable1.getValueAt(i, 8).toString();;
                con.query(query);
               
               
            }
             con.query(query1);
            f.dispose();
        } else {

            JOptionPane.showMessageDialog(null, "Proszę uzupełnić dane ", "INFO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        f.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            new Druk(con, 1, IdFaktura);
            f.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(edycjaFaktura.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        try {
            // TODO add your handling code here:
            UpdateCeny();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jXDatePicker1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dateDWystawienia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextField1;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JTextField txtNrDok;
    // End of variables declaration//GEN-END:variables
}
