/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import db.CennikIndywidualny;
import db.Connector;
import java.awt.LayoutManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Przemek
 */
public class Klient_CenyInd extends javax.swing.JPanel {

    /**
     * Creates new form Klient_CenyInd
     */
    private Connector con;
    DefaultTableModel model;
    private String id;

    public Klient_CenyInd(Connector con, String id) throws SQLException {
        initComponents();
        this.con = con;
        this.id = id;
        model = (DefaultTableModel) jXTable1.getModel();
        wypiszDB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jButton1 = new javax.swing.JButton();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa ", "Cena Netto", "Cena Brutto", "Data Od", "Data Do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jXTable1);

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void wypiszDB() throws SQLException {
        String query;
        query = "   SELECT Towar.Nazwa, Cena, DataPoczatkowa, DataKoncowa FROM TOWAR "
                + " INNER JOIN  CennikIndywidualny ON Towar.Id = CennikIndywidualny.IdTowar "
                + " WHERE CennikIndywidualny.IdKlient =  " + id;
        ResultSet rs = con.querySelect(query);

        while (rs.next()) {
            DecimalFormat df = new DecimalFormat("#,###.00");
            model.addRow(new Object[]{rs.getString(1), df.format(rs.getBigDecimal(2)), "", rs.getDate(3), rs.getDate(4)});
          
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: try {

        JPanel jp = new JPanel();

        listaTowarow lt = null;
        jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
        panelCena pc = new panelCena();

        try {
            lt = new listaTowarow(con, 1);
            jp.add(lt);
            jp.add(pc);
            int response = JOptionPane.showConfirmDialog(null, jp, "Wybierz Klienta",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if(response==0){
            Double brutto;
            
            
            Date dw =pc.jXDatePicker1.getDate();
        
         
        SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
        String date = DATE_FORMAT.format(dw);
        String date2;
        try {
         date2 = DATE_FORMAT.format(pc.jXDatePicker2.getDate());
        }catch (Exception e){
        date2="null";
        }
        
       
            brutto = Double.parseDouble(pc.jTextField2.getText()) * 1.23;
            model.addRow(new Object[]{lt.SelectNazwa, pc.jTextField2.getText(), brutto.toString()});
            
            String query = 
" UPDATE CennikIndywidualny "
                    + " SET DataKoncowa = '"+date+"' "
                    + " WHERE IdTowar = "+lt.SelectID+" AND (DataKoncowa IS NULL  ) "
                    + " INSERT INTO CennikIndywidualny(IdTowar,IdKlient ,Cena, DataPoczatkowa, DataKoncowa) VALUES ("+lt.SelectID+","+id+","+pc.jTextField2.getText()+",'"+date+"','"+date2+"')";
           con.query(query);
            model.setRowCount(0);
            wypiszDB();}
        } catch (SQLException ex) {
            Logger.getLogger(Klient_CenyInd.class.getName()).log(Level.SEVERE, null, ex);

            // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
