/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import db.Connector;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Przemek
 */
public class listaFaktur extends javax.swing.JPanel {

    /**
     * Creates new form listaFaktur
     */
    public String idKlient;
    public Connector con;
    private DefaultTableModel model;
    public String idFaktura = "";
    public String editable;

    public listaFaktur(Connector con) throws SQLException {
        initComponents();

        this.con = con;

        initComponents();
        model = (DefaultTableModel) jXTable1.getModel();

        Date next = new Date(new Date().getTime() - (60 * 1000 * 60 * 60 * 24));
        jXDatePicker2.setDate(next);
        wypiszDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer", "Klient", "Data Sprzedaży", "Data Wystawienia", "Termin Płatności", "Forma płatności", "Kwota", "id", "editable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jXTable1);
        if (jXTable1.getColumnModel().getColumnCount() > 0) {
            jXTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jXTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jXTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jXTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jXTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jXTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jXTable1.getColumnModel().getColumn(4).setMinWidth(100);
            jXTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jXTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jXTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(5).setMaxWidth(100);
            jXTable1.getColumnModel().getColumn(6).setMinWidth(100);
            jXTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(6).setMaxWidth(100);
            jXTable1.getColumnModel().getColumn(7).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(7).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(8).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(8).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        jXSearchField1.setToolTipText("Znajdź fakturę wpisując numer, kod klienta lub NIP kliena");
        jXSearchField1.setPrompt("Znajdź fakturę");
        jXSearchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXSearchField1ActionPerformed(evt);
            }
        });

        jXButton1.setText("Nowa faktura");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        jXDatePicker2.setInheritsPopupMenu(true);
        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });

        jXDatePicker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data wystawienia od");

        jLabel2.setText("do");

        jButton1.setText("Edytuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Podglad");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public void wypiszDB() throws SQLException {
        String query;
        model.setRowCount(0);
        SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");

        String dateDO = "2100-12-31";
        String dateOD = DATE_FORMAT.format(jXDatePicker2.getDate());

        try {
            dateDO = DATE_FORMAT.format(jXDatePicker3.getDate());
        } catch (NullPointerException ex) {
            dateDO = "2100-12-31";
        }

        query = "   SELECT * FROM Faktura  "
                + " WHERE   DataWystawienia BETWEEN '" + dateOD + "' AND '" + dateDO + "' AND numer "
                + "LIKE '%" + jXSearchField1.getText() + "%';";

    
        ResultSet rs = con.querySelect(query);

        while (rs.next()) {
            DecimalFormat df = new DecimalFormat("#,###.00");
            model.addRow(new Object[]{rs.getString(2), rs.getString(9),rs.getDate(14), rs.getDate(3), rs.getDate(4), rs.getString(5), df.format(rs.getDouble(12)), rs.getString(1), rs.getString(13)});
        }

    }

    private void jXSearchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXSearchField1ActionPerformed
        // TODO add your handling code here:
        try {
            wypiszDB();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Klient_Faktury.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXSearchField1ActionPerformed

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame();
        nowaFaktura lk = null;
        try {
            lk = new nowaFaktura(con, f,this);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.add(lk);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setSize(840, 480);
        f.setVisible(true);
        f.setTitle("Hurtownia - Cennik");
        f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
        f.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed
        try {
            // TODO add your handling code here:
            wypiszDB();
        } catch (SQLException ex) {
            Logger.getLogger(Klient_Faktury.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void jXDatePicker3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker3ActionPerformed
        try {
            wypiszDB();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Klient_Faktury.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXDatePicker3ActionPerformed

    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
        // TODO add your handling code here:

       

        try { idFaktura = (String) jXTable1.getValueAt(jXTable1.getSelectedRow(), 7);

            editable = (String) jXTable1.getValueAt(jXTable1.getSelectedRow(), 8);

            if (editable.equals("null")) {
                editable = "1";
                jButton1.setEnabled(true);
            }  
            
            if(editable.equals("0")){
            jButton1.setEnabled(false);
            }
        } catch (NullPointerException e) {
            jButton1.setEnabled(true);
            editable = "1";
        }

        
        if (evt.getClickCount() == 2) {

            try {
                JFrame f = new JFrame();
                podgladFaktury lk = null;

                lk = new podgladFaktury(con, idFaktura, f);

                f.add(lk);
                f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                f.setSize(840, 480);
                f.setVisible(true);
                f.setTitle("Hurtownia - Podgląd Faktury");
                f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
                f.setExtendedState(JFrame.MAXIMIZED_BOTH);
            } catch (SQLException ex) {
                Logger.getLogger(listaFaktur.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
    }//GEN-LAST:event_jXTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!idFaktura.equals("") && !editable.equals("0")) {

            JFrame f = new JFrame();
            edycjaFaktura lk = null;
            try {
                lk = new edycjaFaktura(con, idFaktura, f);
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            f.add(lk);
            f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            f.setSize(840, 480);
            f.setVisible(true);
            f.setTitle("Hurtownia - Cennik");
            f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
            f.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (!idFaktura.equals("")) {

            try {
                JFrame f = new JFrame();
                podgladFaktury lk = null;

                lk = new podgladFaktury(con, idFaktura, f);

                f.add(lk);
                f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                f.setSize(840, 480);
                f.setVisible(true);
                f.setTitle("Hurtownia - Podgląd Faktury");
                f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
                f.setExtendedState(JFrame.MAXIMIZED_BOTH);
            } catch (SQLException ex) {
                Logger.getLogger(listaFaktur.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
