/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package okno;

import db.Connector;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Przemek
 */
public final class podgladFaktury extends javax.swing.JPanel {

    /**
     * Creates new form podgladFaktury
     */
    private final DefaultTableModel model;
    private String IdFirma;
    private final Connector con;
    private Object formaPatnosci;
    private final String IdFaktura;
    JFrame jf;
    private final DecimalFormat df = new DecimalFormat("##0.00");
    Double wnet23 = 00.0;
    Double wbru23 = 00.0;

    Double wnet8 = 00.0;
    Double wbru8 = 00.0;

    Double wnet5 = 00.0;
    Double wbru5 = 00.0;

    Double wnet0 = 00.0;
    Double wbru0 = 00.0;

    public podgladFaktury(Connector con, String IdFaktura, JFrame jf) throws SQLException {
        initComponents();
        this.con = con;
        this.IdFaktura = IdFaktura;
        jComboBox1.removeAllItems();
        this.jf=jf;
        model = (DefaultTableModel) jXTable1.getModel();
        model.setRowCount(0);
        wypisz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNrDok = new javax.swing.JTextField();
        dateDWystawienia = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jXTable2 = new org.jdesktop.swingx.JXTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel7.setText("Notatka");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel1.setText("Kontrahent");

        jLabel2.setText("Numer dokumentu");

        dateDWystawienia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDWystawieniaActionPerformed(evt);
            }
        });

        jLabel3.setText("Data wystawienia");

        jLabel4.setText("Termin płatności");

        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gotówka", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Suma BRUTTO");

        jLabel9.setBackground(new java.awt.Color(0, 204, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("0 ");

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa Towaru", "Ilość", "j.m", "Cena Netto", "VAT", "Wartość Netto", "Wartość VAT", "Wartość Brutto", "ID", "dostepne", "iloscOLD", "dostepOLD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jXTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jXTable1);
        if (jXTable1.getColumnModel().getColumnCount() > 0) {
            jXTable1.getColumnModel().getColumn(8).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(8).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(8).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(9).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(9).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(9).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(10).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(10).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(10).setMaxWidth(0);
            jXTable1.getColumnModel().getColumn(11).setMinWidth(0);
            jXTable1.getColumnModel().getColumn(11).setPreferredWidth(0);
            jXTable1.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        jTextField1.setColumns(20);
        jTextField1.setRows(5);
        jScrollPane4.setViewportView(jTextField1);

        jLabel5.setText("Forma płatnosci");

        jLabel6.setText("Uwagi");

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"23", null, null},
                {"8", null, null},
                {"5", null, null},
                {"0", null, null}
            },
            new String [] {
                "Stawka VAT", "Wartość Netto", "Wartość brutto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jXTable2);

        jButton1.setText("Drukuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edytuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Status");

        jLabel11.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("zł");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dateDWystawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addGap(2, 2, 2)
                                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNrDok, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3))
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel1)))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNrDok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dateDWystawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel7))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel6)))
                    .addContainerGap(307, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void wypisz() throws SQLException {

        String query = "SELECT * FROM Faktura WHERE Id= " + IdFaktura;

        ResultSet rs = con.querySelect(query);

        while (rs.next()) {

            txtNrDok.setText(rs.getString(2));
            IdFirma = rs.getString(8);
            jTextField1.setText(rs.getString(9) + "\n" + rs.getString(10) + "\n" + rs.getString(11));
            dateDWystawienia.setDate(rs.getDate(3));
            jXDatePicker2.setDate(rs.getDate(4));
            jTextArea1.setText(rs.getString(7));
            jTextArea2.setText(rs.getString(6));
            jComboBox1.addItem(rs.getString(5));

            try {
                if (rs.getString(13).equals("0")) {
                    jButton2.setEnabled(false);
                    jLabel11.setText("Zatwierdzona");
                } else {
                    jLabel11.setText("Nie zatwierdzona");
                }
            } catch (NullPointerException ex) {
                jLabel11.setText("Nie zatwierdzona");
            }
        }

        query = " SELECT * FROM PozycjaFaktury INNER JOIN Towar ON Towar = Towar.Id where IdFaktura = " + IdFaktura;
       
        rs = con.querySelect(query);

        while (rs.next()) {
            
            Double dostep = rs.getDouble(4) + rs.getDouble(20);
            model.addRow(new Object[]{rs.getString(12), df.format(rs.getDouble(4)), rs.getString(8), df.format(rs.getDouble(5)), rs.getDouble(6), "", "", "", rs.getString(2), dostep, rs.getString(4)});

        }
        licz();

    }

    private void licz() {
        Double suma;
        suma = 0.00;
        for (int i = 0; i < jXTable1.getRowCount(); i++) {
            String ilosc = jXTable1.getValueAt(i, 1).toString();
            String cNetto = jXTable1.getValueAt(i, 3).toString();
            String VAT = jXTable1.getValueAt(i, 4).toString();

            Double il, cN, V;
            try {
                il = Double.parseDouble(ilosc.replaceAll(",", "."));
                cN = Double.parseDouble(cNetto.replaceAll(",", "."));
                V = Double.parseDouble(VAT.replaceAll(",", "."));

                System.out.println();
                Double wNetto = il * cN;
                Double wVAT = (il * V * cN) / 100;
                Double wBrutto = wNetto + wVAT;
            

                jXTable1.getColumnExt(5).setEditable(true);
                jXTable1.getColumnExt(6).setEditable(true);
                jXTable1.getColumnExt(7).setEditable(true);

                jXTable1.setValueAt(df.format(wNetto), i, 5);
                jXTable1.setValueAt(df.format(wVAT), i, 6);
                jXTable1.setValueAt(df.format(wBrutto), i, 7);

                jXTable1.getColumnExt(5).setEditable(false);
                jXTable1.getColumnExt(6).setEditable(false);
                jXTable1.getColumnExt(7).setEditable(false);

                suma = suma + wBrutto;

                if (V == 23.0) {

                    wnet23 += wNetto;
                    wbru23 += wBrutto;
                } else if (V == 8.0) {
                    wnet8 += wNetto;
                    wbru8 += wBrutto;
                } else if (V == 5.0) {
                    wnet5 += wNetto;
                    wbru5 += wBrutto;
                } else if (V == 0.0) {
                    wnet0 += wNetto;
                    wbru0 += wBrutto;
                }

            } catch (NumberFormatException e) {
            }

        }
        if (wnet23 != 0.0) {
            jXTable2.setValueAt(df.format(wnet23), 0, 1);
            jXTable2.setValueAt(df.format(wbru23), 0, 2);
        } else {
            jXTable2.setValueAt("0,00", 0, 1);
            jXTable2.setValueAt("0,00", 0, 2);
        }

        if (wnet8 != 0.0) {
            jXTable2.setValueAt(df.format(wnet8), 1, 1);
            jXTable2.setValueAt(df.format(wbru8), 1, 2);
        } else {
            jXTable2.setValueAt("0,00", 1, 1);
            jXTable2.setValueAt("0,00", 1, 2);
        }

        if (wnet5 != 0.0) {
            jXTable2.setValueAt(df.format(wnet5), 2, 1);
            jXTable2.setValueAt(df.format(wbru5), 2, 2);
        } else {
            jXTable2.setValueAt("0,00", 2, 1);
            jXTable2.setValueAt("0,00", 2, 2);
        }

        if (wnet0 != 0.0) {
            jXTable2.setValueAt(df.format(wnet0), 3, 1);
            jXTable2.setValueAt(df.format(wbru0), 3, 2);
        } else {
            jXTable2.setValueAt("0,00", 3, 1);
            jXTable2.setValueAt("0,00", 3, 2);
        }
        jLabel9.setText(df.format(suma));

    }
    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked

    }//GEN-LAST:event_jXTable1MouseClicked

    private void jXTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTable1KeyReleased

    }//GEN-LAST:event_jXTable1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Druk druk = new Druk(con, 1, IdFaktura);
        } catch (SQLException ex) {
            Logger.getLogger(podgladFaktury.class.getName()).log(Level.SEVERE, null, ex);
        }
        jf.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jf.dispose();
        JFrame f = new JFrame();
        edycjaFaktura lk = null;
        try {
            lk = new edycjaFaktura(con, IdFaktura, f);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.add(lk);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.setSize(840, 480);
        f.setVisible(true);
        f.setTitle("Hurtownia - Cennik");
        f.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
        f.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dateDWystawieniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDWystawieniaActionPerformed

    }//GEN-LAST:event_dateDWystawieniaActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed

    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dateDWystawienia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextField1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTable jXTable2;
    private javax.swing.JTextField txtNrDok;
    // End of variables declaration//GEN-END:variables
}
